name: Build hyprland

on:
  workflow_dispatch:
  push:
    paths:
      - 'hyprland-git/**'
      - '.copr/**'

jobs:
  main:
    if: |
      github.event_name == 'workflow_dispatch' ||
      contains(github.event.head_commit.message, '[build-all]') ||
      contains(github.event.head_commit.message, '[build-hyprland]') ||
      contains(github.event.head_commit.message, '[build-nvidia]') ||
      contains(github.event.head_commit.message, '[build-legacyrenderer]')
    runs-on: ubuntu-latest
    container:
      image: 'registry.fedoraproject.org/fedora-minimal:latest'

    steps:
      - name: Prepare
        run: |
          microdnf -y install --nodocs --setopt=install_weak_deps=0 \
             copr-cli parallel

      - name: Copr config
        env:
          COPR_CONF: ${{ secrets.COPR_CONFIG }}
        run: |
          mkdir -p ~/.config
          echo "$COPR_CONF" > ~/.config/copr

      - name: Build all
        if: contains(github.event.head_commit.message, '[build-all]')
        run: |
          parallel copr-cli build-package solopasha/hyprland --nowait --name ::: hyprland{,-nvidia,-legacyrenderer}

      - name: Build hyprland
        if: contains(github.event.head_commit.message, '[build-hyprland]')
        run: |
          copr-cli build-package solopasha/hyprland --nowait --name hyprland

      - name: Build hyprland-nvidia
        if: contains(github.event.head_commit.message, '[build-nvidia]')
        run: |
          copr-cli build-package solopasha/hyprland --nowait --name hyprland

      - name: Build hyprland-legacyrenderer
        if: contains(github.event.head_commit.message, '[build-legacyrenderer]')
        run: |
          copr-cli build-package solopasha/hyprland --nowait --name hyprland
